### PR TITLE
i18n for attribute labels

### PR DESCRIPTION
**Pull request by reuhtte**
I don't know if it is correct to apply the translate method with the "app" category. The "app" category is the usual category in yii2 documentation. On the other hand, maybe it's better that every extension has  its own category.

### CODE REVIEW

**Comment by Sammaye** [comment]
Awesome thanks!

**Comment by Sammaye** [comment]
Nah I think it is ok to just slap these in app category, if it becomes a problem we can deal with it later, but I don't see one

**Comment by Sammaye** [comment]
If this extension included it's own translations then we would want a category of it's own but I think currently it might just cause more problems than solve.

**Comment by Sammaye** [comment]
I have been thinking about this some more, ID a very generic label, maybe it is best to make these into their own category, like `yii2.audittrail`

**Comment by Sammaye** [comment]
I decided to change it to the `audittrail` it seems this is the right thing to do the more I think about it https://github.com/Sammaye/yii2-audittrail/commit/7a0435d4955299f32f697a54e81482aa5f57dc49

Let me know if any concerns arise

**Comment by reuhtte** [comment]
No, I think it is ok. I think it is better with its own category. The only scenario I can imagine that would be a mess is if someone install another extension with the same category, or if he wants to use the "audittrail" category for another reason. But that is unlikely.

**Pull request merged**
